### ISSUE TITLE
Add fallback json file for conferences

### ISSUE THREAD

**Issue by abhinayagarwal** [devoxx/MyDevoxxGluon#120]
With the new conference API in place, we need to make sure that we have an equivalent json file for them for correct working of the application without cloudlink configuration.

**Comment by abhinayagarwal** [comment]
Starting the application without GCL config results in:

```
com.sun.javafx.iio.ImageStorageException: No loader for image data
   at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:276)
   at com.sun.javafx.tk.quantum.PrismImageLoader2.loadAll(PrismImageLoader2.java:142)
   at com.sun.javafx.tk.quantum.PrismImageLoader2.<init>(PrismImageLoader2.java:77)
   at com.sun.javafx.tk.quantum.QuantumToolkit.loadImage(QuantumToolkit.java:740)
   at javafx.scene.image.Image.loadImage(Image.java:1073)
   at javafx.scene.image.Image.initialize(Image.java:804)
   at javafx.scene.image.Image.<init>(Image.java:707)
   at com.gluonhq.cloudlink.client.media.MediaClient.loadImage(MediaClient.java:99)
   at com.devoxx.views.helper.Util.getMediaBackgroundImage(Util.java:100)
   at com.devoxx.views.helper.Util.getMediaBackgroundImageView(Util.java:92)
   at com.devoxx.DevoxxDrawerPresenter$Header.<init>(DevoxxDrawerPresenter.java:169)
   at com.devoxx.DevoxxDrawerPresenter.<init>(DevoxxDrawerPresenter.java:66)
   at java.lang.reflect.Constructor.newInstance(Native Method)
   at com.gluonhq.charm.glisten.afterburner.GluonInstanceProvider.apply(GluonInstanceProvider.java:62)
   at com.gluonhq.charm.glisten.afterburner.GluonInstanceProvider.apply(GluonInstanceProvider.java:21)
   at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Injector.java:116)
   at com.devoxx.DevoxxApplication.postInit(DevoxxApplication.java:183)
   at com.gluonhq.charm.glisten.application.MobileApplication.a(SourceFile:272)
   at com.gluonhq.charm.glisten.application.MobileApplication.start(SourceFile:233)
   at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$145(LauncherImpl.java:863)
   at com.sun.javafx.application.LauncherImpl.access$lambda$8(LauncherImpl.java)
   at com.sun.javafx.application.LauncherImpl$$Lambda$9.run(Unknown Source)
   at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$158(PlatformImpl.java:326)
   at com.sun.javafx.application.PlatformImpl.access$lambda$6(PlatformImpl.java)
   at com.sun.javafx.application.PlatformImpl$$Lambda$7.run(Unknown Source)
   at com.sun.javafx.application.PlatformImpl.lambda$null$156(PlatformImpl.java:295)
   at com.sun.javafx.application.PlatformImpl.access$lambda$18(PlatformImpl.java)
   at com.sun.javafx.application.PlatformImpl$$Lambda$19.run(Unknown Source)
   at java.security.AccessController.doPrivileged(AccessController.java:52)
   at com.sun.javafx.application.PlatformImpl.lambda$runLater$157(PlatformImpl.java:294)
   at com.sun.javafx.application.PlatformImpl.access$lambda$5(PlatformImpl.java)
   at com.sun.javafx.application.PlatformImpl$$Lambda$6.run(Unknown Source)
   at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:93)
   at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:52)
   at java.lang.Thread.run(Thread.java:818)
```
