### ISSUE TITLE
Share service fails on Android with targetSDK >= 24

### ISSUE THREAD

**Issue by jperedadnr** [devoxx/MyDevoxxGluon#172]
Trying to share a file throws an exception:
```
10-14 11:00:50.813 26128 26154 W System.err: android.os.FileUriExposedException: file:///storage/emulated/0/Documents/DevoxxBE-badges.csv exposed beyond app through ClipData.Item.getUri()
10-14 11:00:50.814 26128 26154 W System.err: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.net.Uri.checkFileUriExposed(Uri.java:2371)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10216)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10222)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.app.Activity.startActivityForResult(Activity.java:4586)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.app.Activity.startActivityForResult(Activity.java:4544)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.app.Activity.startActivity(Activity.java:4905)
10-14 11:00:50.814 26128 26154 W System.err: 	at android.app.Activity.startActivity(Activity.java:4873)
10-14 11:00:50.814 26128 26154 W System.err: 	at com.gluonhq.charm.down.plugins.android.AndroidShareService.share(AndroidShareService.java:111)
```

This requires a fix in the ShareService. See this [link](https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed)

**Comment by jperedadnr** [comment]
Fixed by #193
