### ISSUE TITLE
Exception when searching schedule

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#208]
An exception occurs when searching for specific keywords.

e.g. "javafx" in DVBE schedule

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.devoxx.views.cell.SearchCell.getCell(SearchCell.java:129)
        at com.devoxx.views.cell.SearchCell.updateItem(SearchCell.java:65)
        at com.gluonhq.impl.charm.a.b.b.h$2.updateItem(SourceFile:198)
        at javafx.scene.control.ListCell.updateItem(ListCell.java:471)
        at javafx.scene.control.ListCell.access$300(ListCell.java:72)
        at javafx.scene.control.ListCell$2.changed(ListCell.java:185)
        at javafx.scene.control.ListCell$2.changed(ListCell.java:175)
        at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:89)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.control.ListView.setItems(ListView.java:390)
        at com.gluonhq.impl.charm.a.b.b.h.e(SourceFile:530)
        at com.gluonhq.impl.charm.a.b.b.h.a(SourceFile:419)
        at com.sun.javafx.binding.ListExpressionHelper$SingleChange.fireValueChangedEvent(ListExpressionHelper.java:239)
        at com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:109)
        at javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:200)
        at javafx.beans.property.ListPropertyBase.lambda$new$39(ListPropertyBase.java:56)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at com.devoxx.views.SearchPresenter.lambda$null$11(SearchPresenter.java:184)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by erwin1** [comment]
fixed by #209
