### ISSUE TITLE
Accessing Android Play Store for review fails

### ISSUE THREAD

**Issue by jperedadnr** [devoxx/MyDevoxxGluon#303]
```
D/GluonAttach(20126):   [Browser Service] Initializing native Browser from OnLoad
D/GluonAttach(20126):   Util :: Load className com/gluonhq/helloandroid/DalvikBrowserService
D/GraalCompiled(20126): Apr 22, 2022 7:29:38 PM com.gluonhq.attach.util.impl.DefaultServiceFactory createInstance
D/GraalCompiled(20126): FINE: Service class for: com.gluonhq.attach.browser.impl.AndroidBrowserService
D/GraalCompiled(20126): Apr 22, 2022 7:29:38 PM com.gluonhq.attach.util.Services get
D/GraalCompiled(20126): FINE: Return service: com.gluonhq.attach.browser.impl.AndroidBrowserService@44b129c1
E/GluonAttach(20126):   Invalid URL: url should start with http:// or https://
D/GraalCompiled(20126): java.io.IOException: Error launching url market://details?id=com.devoxx
D/GraalCompiled(20126):     at com.gluonhq.attach.browser.impl.AndroidBrowserService.launchExternalBrowser(AndroidBrowserService.java:57)
D/GraalCompiled(20126):     at com.devoxx.views.helper.Util.lambda$requestRating$4(Util.java:155)
D/GraalCompiled(20126):     at java.util.Optional.ifPresent(Optional.java:183)
D/GraalCompiled(20126):     at com.devoxx.views.helper.Util.requestRating(Util.java:152)
```

**Comment by jperedadnr** [comment]
A possible fix for now is to replace `market://details?id=com.devoxx` with `https://play.google.com/store/apps/details?id=com.devoxx`. That works but doesn't start the review process.
A better fix for it should be this `ReviewService`: https://github.com/gluonhq/attach/pull/241
