### ISSUE TITLE
Devoxx app crashes when using Twitter Auth

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#347]
When starting OAuth using Twitter on Android Sumsung S23, the app crashes with following catlog

```
03-27 11:28:19.196  2784  3071 D WindowManager: performShow logReadyForDisplay win=Window{c8a21a8 u0 com.samsung.android.app.galaxyfinder/com.samsung.android.app.galaxyfinder.GalaxyFinderActivity} mToken.waitingToShow:true isTransitionSet:true
03-27 11:28:19.196  2784  3071 D WindowManager: Loading animation for app transition. transit=TRANSIT_OLD_CRASHING_ACTIVITY_CLOSE enter=false frame=Rect(0, 0 - 1440, 2932) insets=Rect(0, 0 - 0, 0) surfaceInsets=Rect(0, 0 - 0, 0)
03-27 11:28:19.196  2784  3071 D WindowManager: Loading animation for app transition. transit=TRANSIT_OLD_CRASHING_ACTIVITY_CLOSE enter=true frame=Rect(0, 100 - 1440, 3032) insets=Rect(0, 0 - 0, 0) surfaceInsets=Rect(10, 10 - 10, 10)
03-27 11:28:19.196  2784  3071 D WindowManager: Loading animation for app transition. transit=TRANSIT_OLD_CRASHING_ACTIVITY_CLOSE enter=true frame=Rect(0, 0 - 1440, 3088) insets=Rect(0, 100 - 0, 56) surfaceInsets=Rect(0, 0 - 0, 0)
03-27 11:28:19.196  2784  3071 V WindowManager: Setting visibility of Window{ca38bea u0 com.devoxx/com.gluonhq.helloandroid.MainActivity EXITING}: false, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:1246 com.android.server.wm.WindowToken.setClientVisible:431 com.android.server.wm.ActivityRecord.setClientVisible:7662 com.android.server.wm.ActivityRecord.onAnimationFinished:8561 com.android.server.wm.ActivityRecord.postApplyAnimation:6223
03-27 11:28:19.196  2784  3071 W WindowManager: Exception thrown during dispatchAppVisibility Window{ca38bea u0 com.devoxx/com.gluonhq.helloandroid.MainActivity EXITING}
03-27 11:28:19.196  2784  3071 W WindowManager: android.os.DeadObjectException
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:662)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:658)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:4197)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1246)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:431)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:7662)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:8561)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:6223)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6195)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:6199)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1269)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:298)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:1182)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:1022)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:950)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:185)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:134)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:123)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:65)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:226)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.Looper.loop(Looper.java:313)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
03-27 11:28:19.196  2784  3071 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
03-27 11:28:19.197  2784  3071 E WindowManager: win=Window{ca38bea u0 com.devoxx/com.gluonhq.helloandroid.MainActivity EXITING} destroySurfaces: appStopped=false cleanupOnResume=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.ActivityRecord.destroySurfaces:6509 com.android.server.wm.ActivityRecord.destroySurfaces:6490 com.android.server.wm.WindowState.onExitAnimationDone:5965 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:8578 com.android.server.wm.ActivityRecord.postApplyAnimation:6223
03-27 11:28:19.197  2784  3071 I WindowManager: Destroying surface Surface(name=com.devoxx/com.gluonhq.helloandroid.MainActivity$_31649)/@0x7e555b2 called by com.android.server.wm.WindowStateAnimator.destroySurface:942 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:536 com.android.server.wm.WindowState.destroySurfaceUnchecked:4303 com.android.server.wm.WindowState.destroySurface:4277 com.android.server.wm.ActivityRecord.destroySurfaces:6509 com.android.server.wm.ActivityRecord.destroySurfaces:6490 com.android.server.wm.WindowState.onExitAnimationDone:5965 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda10.accept:2
03-27 11:28:19.197  2784  3071 D RestrictionPolicy: isScreenCaptureEnabled : ret=true userId=0
03-27 11:28:19.197  2784  3071 I WindowManager: Cancelling animation restarting=true, leash=Surface(name=Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation)/@0xcd624ab
03-27 11:28:19.197  2784  3071 I WindowManager: Reparenting to original parent: Surface(name=WindowToken{f2d9176 type=2011 android.os.Binder@3f5c11})/@0x6e70831, destroy=false, surface=Surface(name=69844a InputMethod)/@0x38bdcd8
03-27 11:28:19.197  2784  3071 I WindowManager: Reparenting to leash, surface=Surface(name=69844a InputMethod)/@0x38bdcd8, leashParent=Surface(name=WindowToken{f2d9176 type=2011 android.os.Binder@3f5c11})/@0x6e70831
03-27 11:28:19.197  1792  2029 I SurfaceFlinger: id=58126 createSurf, flag=24004, Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58126
03-27 11:28:19.198  2784  3071 D WindowManager: makeSurface duration=1 leash=Surface(name=Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation)/@0xac3eb8
03-27 11:28:19.198  2784  3071 V WindowManager: Nulling last startingData
03-27 11:28:19.198  2784  3071 D ActivityTaskManager: mStartingWindow and mStartingData is null for token=ActivityRecord{81add67 u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity} t956}
03-27 11:28:19.198  2784  3071 V WindowManager: performShowLocked: mDrawState=HAS_DRAWN in Window{7cb0e5d u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity}
03-27 11:28:19.199  2784  3071 I WindowManager: Reparenting to leash, surface=Surface(name=de4b670 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity)/@0xeb39ff7, leashParent=Surface(name=ActivityRecord{81add67 u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity} t956})/@0xd428e64
03-27 11:28:19.199  1792  2029 I SurfaceFlinger: id=58127 createSurf, flag=24004, Surface(name=de4b670 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity)/@0xeb39ff7 - animation-leash of window_animation#58127
03-27 11:28:19.199  2784  3071 D WindowManager: makeSurface duration=0 leash=Surface(name=Surface(name=de4b670 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity)/@0xeb39ff7 - animation-leash of window_animation)/@0x21148cd
03-27 11:28:19.199  2784  3071 V WindowManager: performShowLocked: mDrawState=HAS_DRAWN in Window{de4b670 u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity}
03-27 11:28:19.200  2784  3071 D ActivityTaskManager: mStartingWindow and mStartingData is null for token=ActivityRecord{a31cf7e u0 com.samsung.android.app.galaxyfinder/.GalaxyFinderActivity} t954}
03-27 11:28:19.200  2784  3071 V WindowManager: performShowLocked: mDrawState=HAS_DRAWN in Window{c8a21a8 u0 com.samsung.android.app.galaxyfinder/com.samsung.android.app.galaxyfinder.GalaxyFinderActivity}
03-27 11:28:19.200  1792  1792 I Layer   : id=58103 removedFromDrawingState com.devoxx/com.gluonhq.helloandroid.MainActivity$_31649#58103 (189)
03-27 11:28:19.200  1792  1792 I Layer   : id=58106 removedFromDrawingState Bounds for - com.devoxx/com.gluonhq.helloandroid.MainActivity@0#58106 (189)
03-27 11:28:19.200  1792  1792 I Layer   : id=58107 removedFromDrawingState SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0#58107 (189)
03-27 11:28:19.200  1792  1792 I Layer   : id=58109 removedFromDrawingState Background for SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0#58109 (189)
03-27 11:28:19.200  1792  1792 I Layer   : id=58108 removedFromDrawingState SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0(BLAST)#58108 (189)
03-27 11:28:19.200  2784  4097 D EdgeLightingPolicyManager: isAcceptableApplication:  pkg=com.android.systemui , range=1 , includeAllApp=false , userId=-2 , infoRange=0 , infoCategory=0
03-27 11:28:19.200  2784  4097 D EdgeLightingPolicyManager: isAcceptableApplication - accept rechecked by isEdgeLightingAllowed = true uid = 10041
03-27 11:28:19.200  2784  4097 D EdgeLightingPolicyManager: isAcceptableApplication: getRejectablePolicy true
03-27 11:28:19.200  2784  2800 W System  : A resource failed to call HardwareBuffer.close.
03-27 11:28:19.200  2784  2800 W System  : A resource failed to call close.
03-27 11:28:19.202  2784  3071 D ActivityManagerPerformance: AMP_release() ACT_RESUME
03-27 11:28:19.202  2784  3071 I SemDvfsHyPerManager: acquire hyper - AMS_RESUME_TAIL/2784@20, type = -999
03-27 11:28:19.202  2784  3071 I SemDvfsHyPerManager: acquire hyper - AMS_ACT_LAZY/2784@21, type = -999
03-27 11:28:19.202  2784  3071 D ActivityManagerPerformance: AMP_acquire() TAIL
03-27 11:28:19.202  2784  3071 D ActivityManagerPerformance: AMP_release() APP_SWITCH
03-27 11:28:19.202  1792  1792 D SurfaceFlinger: Display 4630947093241269891 HWC layers:
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:      CLIENT | 0xb400006f3e106e00 | 0100 | RGBx_8888    |    0.0  618.0 2316.0 1698.0 |    0    0 1440 3088 | Wallpaper BBQ wrapper#99
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f3e873180 | 0100 | RGBA_8888    |    0.0    0.0 1440.0  100.0 |    0    0 1440  100 | StatusBar$_4595#95
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f4d011200 | 0100 | RGBA_8888    |    0.0    0.0   67.0  458.0 | 1373  683 1440 1141 | com.samsung.android.app.cocktailbars[...]rvice.CocktailBarService$_8700#57752
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f3e029c80 | 0100 | RGBA_8888    |    0.0    0.0  518.0   56.0 |  922 3032 1440 3088 | SGestureOverlayWindow$_5192#57292
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f4d011600 | 0100 | RGBA_8888    |    0.0    0.0 1440.0  180.0 |    0 2908 1440 3088 | NavigationBar0$_4595#16985
03-27 11:28:19.202  1792  1792 D SurfaceFlinger:
03-27 11:28:19.203  4595  4595 I FaceWidgetPositionAlgorithm: getClockContainerHeight() supplier = 386, bottom margin = 0, real height = 476
03-27 11:28:19.203  1792  2030 I SurfaceFlinger: id=58128 createSurf, flag=80000, 9bd8d26 ActivityRecordInputSink com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity#58128
03-27 11:28:19.203  4595  4595 I FaceWidgetPositionAlgorithm: getClockContainerHeight() supplier = 386, bottom margin = 90, real height = 476
03-27 11:28:19.203  4595  4595 I FaceWidgetPositionAlgorithm: getMediaContainerHeight() height = 652 container Visibility = 8, isValid = false, mIsDozing = false, fraction = 1.0, source = 0, target = 0
03-27 11:28:19.203  4595  4595 I FaceWidgetPositionAlgorithm: getMediaContainerHeight() supplier = 0
03-27 11:28:19.204  1792  3164 I SurfaceFlinger: id=58129 createSurf, flag=20004, Dim Layer for - WindowedMagnification:0:31#58129
03-27 11:28:19.204  1658  1735 I HYPER-HAL: [RequestManager.cpp]releaseLocked(): Released ID : 3957920
03-27 11:28:19.204  1658  1735 I HYPER-HAL: [RequestManager.cpp]acquire(): Acquired ID : 3932630  [2784 / 20]    HINT : AMS_RESUME_TAIL    list :
03-27 11:28:19.205  2784  3071 I WindowManager: Reparenting to leash, surface=Surface(name=Dim Layer for - WindowedMagnification:0:31)/@0xe41b30b, leashParent=Surface(name=WindowedMagnification:0:31)/@0xd573127
03-27 11:28:19.205  1648 21582 I sensors-hal: handle_sns_client_event:526, [66493] mag_sample_cal: ts=1119275043530904 ns; cal = [20.617310, 21.993042, -75.706459], uncal = [-1254.622681, -167.366959, -196.366455], bias = [-1275.239990, -189.360001, -120.659996], status=3
03-27 11:28:19.205  1792  3168 I SurfaceFlinger: id=58130 createSurf, flag=24000, Surface(name=Dim Layer for - WindowedMagnification:0:31)/@0xe41b30b - animation-leash of dimmer#58130
03-27 11:28:19.205  2784  3071 D WindowManager: makeSurface duration=0 leash=Surface(name=Surface(name=Dim Layer for - WindowedMagnification:0:31)/@0xe41b30b - animation-leash of dimmer)/@0x5792401
03-27 11:28:19.206  4595  4595 D PluginAODManager: onNotificationInfoUpdated() 0
03-27 11:28:19.206  4595  4595 I AODNotificationManager: updateVisibleNotifications: 0
03-27 11:28:19.206  1658  1735 I HYPER-HAL: [RequestManager.cpp]acquire(): Acquired ID : 3935436  [2784 / 21]    HINT : AMS_ACT_LAZY    list :
03-27 11:28:19.207  1792  2029 I SurfaceFlinger: id=58101 Removed 4748e58 ActivityRecordInputSink com.devoxx/com.gluonhq.helloandroid.MainActivity#58101 (192)
03-27 11:28:19.207  1792  3164 I SurfaceFlinger: id=58081 Removed Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58081 (192)
03-27 11:28:19.207  1792  3163 I SurfaceFlinger: id=58131 createSurf, flag=24004, Task=955#58131
03-27 11:28:19.207  2784  3067 D [secipm]: mSecIpmManager report to nap
03-27 11:28:19.207  2784  3067 I PkgPredictorService-SecIpmManagerServiceImpl: reportToNAP uid:1000 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity thisTime:140
03-27 11:28:19.208  2784  3071 D ActivityTaskManager: mStartingWindow and mStartingData is null for token=ActivityRecord{81add67 u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity} t956}
03-27 11:28:19.208  1792  1792 I Layer   : id=58102 removedFromDrawingState ca38bea com.devoxx/com.gluonhq.helloandroid.MainActivity#58102 (193)
03-27 11:28:19.208  1792  1792 I Layer   : id=58111 removedFromDrawingState Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58111 (193)
03-27 11:28:19.208  1792  1792 I Layer   : id=58094 removedFromDrawingState ActivityRecord{90f9bb1 u0 com.devoxx/com.gluonhq.helloandroid.MainActivity} t955}#58094 (193)
03-27 11:28:19.208  1792  1792 I Layer   : id=58101 removedFromDrawingState 4748e58 ActivityRecordInputSink com.devoxx/com.gluonhq.helloandroid.MainActivity#58101 (193)
03-27 11:28:19.208  1792  1792 I Layer   : id=58093 removedFromDrawingState Task=955#58093 (193)
03-27 11:28:19.208  1792  1792 I Layer   : id=58131 removedFromDrawingState Task=955#58131 (193)
03-27 11:28:19.208  1792  1792 I SurfaceFlinger: id=58131 Removed Task=955#58131 (193)
03-27 11:28:19.208  1792  1792 I SurfaceFlinger: id=58103 Removed com.devoxx/com.gluonhq.helloandroid.MainActivity$_31649#58103 (193)
03-27 11:28:19.208  1792  1792 I SurfaceFlinger: id=58102 Removed ca38bea com.devoxx/com.gluonhq.helloandroid.MainActivity#58102 (193)
03-27 11:28:19.208  1792  1792 I SurfaceFlinger: id=58111 Removed Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58111 (193)
03-27 11:28:19.208  1792  1792 I SurfaceFlinger: id=58094 Removed ActivityRecord{90f9bb1 u0 com.devoxx/com.gluonhq.helloandroid.MainActivity} t955}#58094 (193)
03-27 11:28:19.208  1792  1792 E ClientCache: failed to get buffer, invalid process token
03-27 11:28:19.209  1792  1792 I Layer   : id=58081 Destroyed Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58081
03-27 11:28:19.209  1792  1792 E BpTransactionCompletedListener: Failed to transact (-32)
03-27 11:28:19.209  1792  1792 I Layer   : id=58103 Destroyed com.devoxx/com.gluonhq.helloandroid.MainActivity$_31649#58103
03-27 11:28:19.209  1792  1792 I Layer   : id=58106 Destroyed Bounds for - com.devoxx/com.gluonhq.helloandroid.MainActivity@0#58106
03-27 11:28:19.209  1792  1792 I Layer   : id=58107 Destroyed SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0#58107
03-27 11:28:19.209  1792  1792 I Layer   : id=58109 Destroyed Background for SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0#58109
03-27 11:28:19.209  1792  1792 E BpTransactionCompletedListener: Failed to transact (-32)
03-27 11:28:19.209  2784  3070 W ActivityManager: setHasOverlayUi called on unknown pid: 31649
03-27 11:28:19.209  1792  1792 I Layer   : id=58108 Destroyed SurfaceView[com.devoxx/com.gluonhq.helloandroid.MainActivity]@0(BLAST)#58108
03-27 11:28:19.210  1792  1792 I Layer   : id=58131 Destroyed Task=955#58131
03-27 11:28:19.210  1792  1792 I Layer   : id=58111 Destroyed Surface(name=69844a InputMethod)/@0x38bdcd8 - animation-leash of insets_animation#58111
03-27 11:28:19.210  1792  1792 I Layer   : id=58094 Destroyed ActivityRecord{90f9bb1 u0 com.devoxx/com.gluonhq.helloandroid.MainActivity} t955}#58094
03-27 11:28:19.210  1792  1792 I Layer   : id=58102 Destroyed ca38bea com.devoxx/com.gluonhq.helloandroid.MainActivity#58102
03-27 11:28:19.210  1792  1792 I Layer   : id=58101 Destroyed 4748e58 ActivityRecordInputSink com.devoxx/com.gluonhq.helloandroid.MainActivity#58101
03-27 11:28:19.210  5192  5192 I RecentsView: onTaskRemoved() taskId : 955
03-27 11:28:19.210  5192  5192 I TopTaskTracker: onTaskRemoved : taskId = 955
03-27 11:28:19.211  1658  1735 I HYPER-HAL: [RequestManager.cpp]releaseLocked(): Released ID : 3938243
03-27 11:28:19.210  5192  5192 I RecentsView: onTaskRemoved() taskId : 955
03-27 11:28:19.211  5192  5192 I TopTaskTracker: onTaskRemoved : taskId = 955
03-27 11:28:19.211  2784  6405 D WindowManager: finishDrawingWindow: Window{7cb0e5d u0 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity} mDrawState=HAS_DRAWN seqId=0
03-27 11:28:19.211  2784  3067 I ActivityTaskManager: Displayed com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity: +140ms
03-27 11:28:19.211  2784  3067 I Pageboost: Launch time gathered : pid 31545 com.samsung.android.lool 140
03-27 11:28:19.212  5432  5432 E pageboostd: Received HALT command code 2
03-27 11:28:19.213  1792  1792 D SurfaceFlinger: Display 4630947093241269891 HWC layers:
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      CLIENT | 0xb400006f3e106e00 | 0100 | RGBx_8888    |    0.0  618.0 2316.0 1698.0 |    0    0 1440 3088 | Wallpaper BBQ wrapper#99
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      CLIENT | 0xb400006f342c0280 | 0100 | RGBA_8888    |    0.0    0.0 1440.0 3088.0 |    0    0 1440 3088 | com.samsung.android.app.galaxyfinder[...]rActivity$_27654#58113 (blurRegions)
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f3e153f80 | 0100 | RGBA_8888    |    0.0    0.0 1440.0  100.0 |    0    0 1440  100 | StatusBar$_4595#95
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f4d011200 | 0100 | RGBA_8888    |    0.0    0.0   67.0  458.0 | 1373  683 1440 1141 | com.samsung.android.app.cocktailbars[...]rvice.CocktailBarService$_8700#57752
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f3e029c80 | 0100 | RGBA_8888    |    0.0    0.0  518.0   56.0 |  922 3032 1440 3088 | SGestureOverlayWindow$_5192#57292
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:      DEVICE | 0xb400006f4d011600 | 0100 | RGBA_8888    |    0.0    0.0 1440.0  180.0 |    0 2908 1440 3088 | NavigationBar0$_4595#16985
03-27 11:28:19.213  1792  1792 D SurfaceFlinger:
03-27 11:28:19.215  2784  5390 D FreecessController: com.instagram.android(10405) is important[19] isUidIdle : true
03-27 11:28:19.215  2784  5390 D FreecessController: com.google.android.apps.photos(state: Initial -> Freezeable, Reason: uidIdle)
03-27 11:28:19.215  2784  5390 D FreecessController: com.twitter.android(state: Initial -> Freezeable, Reason: uidIdle)
03-27 11:28:19.215  2784  5390 D FreecessController: com.reddit.frontpage(state: Initial -> Freezeable, Reason: uidIdle)
03-27 11:28:19.225  1648 21585 I sensors-hal: handle_sns_std_sensor_event:139, [33247] Pressure 1021.515, cal -0.010, sw_offset 0.000
03-27 11:28:19.225  2784  4097 D InputDispatcher: Focus entered window (0): de4b670 com.samsung.android.lool/com.samsung.android.sm.iafd.ui.AppErrorDialogActivity
```

**Comment by jperedadnr** [comment]
Fixed with #350
